#
# Building for BDring new 6x board
#

#
# NOTE: PlatformIO support is provided by the community and platformio.ini is
# not maintained or tested by the repo owner.
# Please submit a PR with bug fixes and enhancments.
#

[platformio]
src_dir = main
include_dir = main

[wifi_networking]
build_flags =

[env:esp32doit-devkit-v1]
platform = espressif32@~4.0.0
framework = espidf
board = esp32doit-devkit-v1
; board_build.partitions = partitions_s3_8m.csv
board_build.partitions = partitions.csv

board_build.embed_files =
    main/embedded/favicon.ico
    main/embedded/ap_login.html
    main/embedded/index.html.gz

build_flags =
    -Wimplicit-fallthrough=1
    -Wno-missing-field-initializers
    -Wno-maybe-uninitialized
    -Wno-stringop-truncation
    -DCONFIG_IDF_TARGET_ESP32=1
    -DCOMPATIBILITY_LEVEL=10
    ; -DY_AUTO_SQUARE=1   
    ; -DDRIVER_SPINDLE_PWM_ENABLE=1
    ; -DSDCARD_ENABLE=2
    ; -DNETWORK_STA_HOSTNAME=grblMKS_DLC32
    ; -DPROBE_ENABLE=1
    ; -DPROBE_PIN=GPIO_NUM_22
    -DSPINDLE_DIRECTION_PIN=GPIO_NUM_25

monitor_speed=115200

lib_compat_mode = off
