#
# Building for BDring new 6x board
#

#
# NOTE: PlatformIO support is provided by the community and platformio.ini is
# not maintained or tested by the repo owner.
# Please submit a PR with bug fixes and enhancments.
#

[platformio]
src_dir = main
include_dir = main

[wifi_networking]
build_flags =

[env:e2d-grblhal-tinybee]
platform = espressif32 @ ~4.0.0
framework = espidf
board = esp32doit-devkit-v1
board_build.partitions = partitions.csv

board_build.embed_files =
    main/embedded/favicon.ico
    main/embedded/ap_login.html
    main/embedded/index.html.gz

; build_type = release
build_type = debug

build_flags =
    -Os
    -Wimplicit-fallthrough=1
    -Wno-missing-field-initializers
    -Wno-maybe-uninitialized
    -Wno-stringop-truncation
    -DCONFIG_IDF_TARGET_ESP32=1
    -DTTMC_STEALTHCHOP=0
    -DLWIP_HTTPD_CUSTOM_FILES=0
    -DLWIP_HTTPD_DYNAMIC_HEADERS=1
    -DLWIP_HTTPD_SUPPORT_V09=0
    -DLWIP_HTTPD_SUPPORT_11_KEEPALIVE=1
    -DLWIP_HTTPD_SUPPORT_POST=1
    -DLWIP_HTTPD_DYNAMIC_FILE_READ=1
    -DCONTROL_ENABLE=6
    ;-DBLOCK_BUFFER_SIZE=512




monitor_speed=115200
monitor_filters =
    esp32_exception_decoder
    time
monitor_echo = yes  

lib_compat_mode = off
